# Generated by Django 5.0.6 on 2024-06-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('COUNTRY', 'Country'), ('REGION', 'Region'), ('CITY', 'City'), ('VILLAGE', 'Village'), ('DISTRICT', 'District'), ('STREET', 'Street'), ('ADDRESS', 'Address')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('unit_number', models.CharField(blank=True, max_length=20)),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='website.location', verbose_name='related country')),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='website.location', verbose_name='related district')),
                ('region_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='website.location', verbose_name='related region')),
                ('settlement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_village', to='website.location', verbose_name='related city or village')),
                ('street_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='website.location', verbose_name='related street')),
            ],
        ),
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('architect_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_death', models.DateField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('birth_location_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.location', verbose_name='the related location')),
            ],
        ),
    ]
