# Generated by Django 5.0.6 on 2024-06-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_architect_fathers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architect',
            name='biography',
        ),
        migrations.AlterField(
            model_name='architect',
            name='birth_location_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.location', verbose_name='birth location'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='fathers name'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='nickname'),
        ),
    ]
