# Generated by Django 5.0.6 on 2024-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_architect_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='biography',
            field=models.TextField(blank=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='date_of_death',
            field=models.DateField(null=True, verbose_name='date of death'),
        ),
    ]
