# Generated by Django 5.0.6 on 2024-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_architect_biography_alter_architect_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='date of death'),
        ),
    ]
