# Generated by Django 5.0.6 on 2024-06-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_architect_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='birth_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.location', verbose_name='birth location'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='fathers name'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nickname'),
        ),
    ]
